server:
  port: 3001

#Spring相关配置
spring:
  profiles:
    active: prod
  application:
    name: easyj-dwz
  datasource:
    driver-class-name: ${easyj.datasource.mysql.driver-class-name}
    url: jdbc:mysql://10.1.50.112:3306/easyj-dwz?autoReconnect=true&failOverReadOnly=false&useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: ${easyj.crypto.decrypt('DQuf6oN5c0bQIyI/VjVHF+57JRCelEcjA1GSlAguH7rM0rkhdrf8XTIthHMYena77jCO4+uO0DBy6A+6z0vauvpqPLKTkcSO4YMQb2sAJiXHjYKdvjDEqW0MDjnT1ZdZS/Ed+pFJo7i7V5TqDtFiuiDJ4xFV5vejWihX38aRszA=')}
  redis:
    host: 10.1.50.112


#序列相关配置
easyj.sequence:
  type: redis #序列服务类型（单应用时，建议配置为：atomic-long，集群时，建议配置为：redis；虽然还有db模式，但不建议使用。）


#日志相关配置
easyj.logging.logback:
  kafka-appender:
    enabled: false
    #bootstrap-servers: ${spring.kafka.bootstrap-servers:127.0.0.1:9092} #默认同步spring.kafka的配置
  logstash-appender:
    enabled: false
    destination: 10.1.50.114:4560 #对应logstash提供的地址
