codecov:
  token: 659ad758-80af-46f7-824d-42d208322902
  require_ci_to_pass: yes
coverage:
  status:
    patch: no
    project:
      default:
        threshold: 1%
        if_not_found: success
    changes: no
  precision: 2
  range: "40...100"
ignore:
  - ".gitee/.*"
  - ".github/.*"
  - "LICENSE"
  - "*.md"
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
