server:
  port: 3002

spring:
  profiles:
    active: prod
  application:
    name: easyj-websocket


#日志相关配置
easyj.logging.logback:
  kafka-appender:
    enabled: false
    #bootstrap-servers: ${spring.kafka.bootstrap-servers:127.0.0.1:9092} #默认同步spring.kafka的配置
  logstash-appender:
    enabled: false
    destination: 10.1.50.114:4560 #对应logstash提供的地址
