name: build

on:
  push:
    branches: [ develop,master ]
  pull_request:
    branches: [ develop,master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ 8, 11, 17 ]
        os: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        # https://docs.github.com/cn/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context
        run: mvn clean install -B -Pcicd -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0