name: "Codecov"

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  test:
    name: "Codecov"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Java JDK
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'zulu'
          java-version: 8

      - name: Run Test With Maven
        # https://docs.github.com/cn/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context
        run: mvn clean install -e -B -Pcicd -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;

      - name: Codecov
        uses: codecov/codecov-action@v2.1.0