#################################################################################
# 此action会发布一个固定的 'latest-SNAPSHOT' 版本，用于 'easyj-samples' 每周自动化测试. #
#################################################################################

name: "Publish To OSS for easyj-samples"

on:
  schedule:
    - cron: '0 1 * * 6'

jobs:
  publish:
    name: "Publish To OSS for easyj-samples"
    runs-on: ubuntu-latest
    steps:
      # step 1
      - name: "Checkout"
        uses: actions/checkout@v2.4.0

      # step 2
      - name: "Setup Java JDK"
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'zulu'
          java-version: 8
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD

      # step 3
      - name: "Import GPG-SECRET-KEY"
        run: |
          cat <(echo -e "${{ secrets.GPG_SECRET_KEY }}") | gpg --batch --import

      # step 4
      - name: "Package and Publish-To-OSS"
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          mvn -T 4C clean deploy -Ppublish-auto -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} -Drevision=latest-SNAPSHOT -Duser.timezone=GMT+0 --batch-mode -e -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
