name: "Test"

on:
  push:
    branches: [ develop, master, test*, spring-boot_* ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 17 ]
        springboot: [
            2.6.4,
            2.5.10,
            2.4.13,
            2.3.12.RELEASE,
            2.2.13.RELEASE,
            #2.1.18.RELEASE,
            #2.0.9.RELEASE,
            #1.5.22.RELEASE,
            #1.4.7.RELEASE,
            #1.3.8.RELEASE,
            #1.2.8.RELEASE,
            #1.1.12.RELEASE,
            #1.0.2.RELEASE
        ]
    steps:
      # step 1
      - name: "Checkout"
        uses: actions/checkout@v2.4.0

      # step 2
      - name: "Setup Java JDK"
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      # step 3
      - name: "Run Test With Maven"
        # https://docs.github.com/cn/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context
        run: if [ "${{ matrix.java }}" == "8" ]; then
            mvn clean install -e -B -Pcicd8 -Duser.timezone=GMT+0 -Dspring-boot.version=${{ matrix.springboot }} -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
          else
            mvn clean install -e -B -Pcicd  -Duser.timezone=GMT+0 -Dspring-boot.version=${{ matrix.springboot }} -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn;
          fi


      # step 4
      - name: "Codecov"
        if: matrix.java == '8' && matrix.springboot == '2.6.4' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master')
        uses: codecov/codecov-action@v2.1.0
